### ISSUE TITLE
Inspector Widget

### ISSUE THREAD

**Issue by Manschu** [SoftwareprojektGameEngine/GEENIE#5]
Ich bin der Meinung das es sinnlos ist nen extra inspectorwidget zu erstellen, da der ganze code dazu ja eh im core generisch erstellt wird

**Comment by Manschu** [comment]
also könnten wir uns den punkt im backlog sparen...

**Comment by Dontsoft** [comment]
Die Widgets müssen trotzdem designed werden.
Die *.ui files liegen dann im Core. Das muss schon drin bleiben

**Comment by Dontsoft** [comment]
Dazu muss allerdings kein eigenes Projekt erstellt werden, wenn du das meinst.
